### ISSUE TITLE
assemble main.py subcommand only working when verbose switch is enabled

### ISSUE THREAD

**Issue by ethandhunt** [ethandhunt/bfa#3]
(reason for weird scroll is that this is copy-pasted from a neovim terminal window)
```
13:54:20 [ethan@ethan-ubuntu ~/Documents/bf/bfa] $ ./main.py assemble . test.bfa0 test.bf                                                                                
recursiveClean('+>{+}65<.')                                                                                                                                              
recursiveClean('+')                                                                                                                                                      
repeatNum: 65                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                       
  File "/home/ethan/Documents/bf/bfa/./main.py", line 714, in <module>                                                                                                   
    main()                                                                                                                                                               
  File "/home/ethan/Documents/bf/bfa/./main.py", line 703, in main                                                                                                       
    f(*args[1:])                                                                                                                                                         
  File "/home/ethan/Documents/bf/bfa/./main.py", line 570, in _0                                                                                                         
    if lastBF != '':                                                                                                                                                     
UnboundLocalError: local variable 'lastBF' referenced before assignment                                                                                                  
13:54:30 [ethan@ethan-ubuntu ~/Documents/bf/bfa] $ ./main.py assemble . test.bfa0 test.bf -v                                                                             
recursiveClean('+>{+}65<.')                                                                                                                                              
last: ''                                                                                                                                                                 
last: ''                                                                                                                                                                 
last: ''                                                                                                                                                                 
last: '+'                                                                                                                                                                
recursiveClean('+')                                                                                                                                                      
last: ''                                                                                                                                                                 
repeatNum: 65                                                                                                                                                            
last: ''                                                                                                                                                                 
last: ''                                                                                                                                                                 
last: ''                                                                                                                                                                 
Tokens:                                                                                                                                                                  
<TOKEN [000:067]>       ('bf', +>+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++<.)                                                                    
cellRefs: {}                                                                                                                                                             
compiled: '+>+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++<.'
```

**Comment by ethandhunt** [comment]
(numbers on side are relative to cursor)
```py
  4         if 'v' in flags or 'verbose' in flags:
  5             print(f'{ansi.bright.yellow}Tokens:{ansi.reset}')
  6             lastBF = ''
  7             lastBFIndex = 0
  8             for i, token in enumerate(tokens):              
  9                 if token[0] == 'goto':                                                                                                                               
 10                     if lastBF != '':                                                                                                                                 
 11                         if lastBFIndex != i-1:                                                                                                                       
 12                             print(f'{ansi.bright.yellow}<TOKEN [{lastBFIndex:03}:{i-1:03}]>\t{ansi.bright.green}(\'bf\', {lastBF})')                                 
 13                                                                                                                                                                      
 14                         else:                                                                                                                                        
 15                             print(f'{ansi.bright.yellow}<TOKEN [{i-1}]>\t\t{ansi.bright.green}(\'bf\', {lastBF})')
 16                                                                                                                                                                      
 17                         lastBF = ''                                                                                                                                  
 18                     print(f'{ansi.bright.yellow}<TOKEN [{i}]>\t\t{ansi.bright.green}{repr(token)}{ansi.reset}')                                                      
 19                                                                                                                                                                      
 20                 if token[0] == 'bf':                                                                                                                                 
 21                     if lastBF == '':                                                                                                                                 
 22                         lastBFIndex = i                                                                                                                              
 23                                                                                                                                                                      
 24                     lastBF += token[1]                                                                                                                               
 25                                                                                                                                                                      
 26         if lastBF != '':                                                                                                                                             
 27             if lastBFIndex != i-1:                                                                                                                                   
 28                 print(f'{ansi.bright.yellow}<TOKEN [{lastBFIndex:03}:{i-1:03}]>\t{ansi.bright.green}(\'bf\', {lastBF})')                                             
 29                                                                                                                                                                      
 30             else:                                                                                                                                                    
 31                 print(f'{ansi.bright.yellow}<TOKEN [{i-1}]>\t\t{ansi.bright.green}(\'bf\', {lastBF})')
```

Indentation issue
After fixing indentation it no longer fails when assembling without the verbose switch
